name: MOE

channels:
  - conda-forge
  - fastai
  
dependencies:
  - python>=3.7
  - pandas
  - matplotlib
  - jupyterlab
  - lxml
  - seaborn
  - twine
  - mkdocs
  - mkdocs-material
  - nbdev
  - python-dotenv
  - scikit-learn
  - scikit-optimize
  - typer
  - tqdm
  - pip
  
  - pip:
      - -e .[cicd,research]
      - mkdocs-material-extensions
      - mkdocstrings
      - configparser
      - junix
      - entsoe-py
      - xmltodict